import { describe, expect, it } from 'vitest'
import { analyze, defineConfig } from '../src'

describe('find unused file list', () => {
  it('find unused file list', async () => {
    expect(await analyze(['./examples/src/main.ts'], {
      alias: {
        '@': './examples/src'
      },
      exclude: ['**/services/**/*'],
      supSuffix: ['.ts', '.tsx']
    })).toMatchInlineSnapshot(`
      {
        "circularDepMap": Map {
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/stores/useUserStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/stores/useLmsStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Footer.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useRepoForks.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useRepoForks.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCooperator.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/stores/useCourseStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/FileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/FileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useClassinExam.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/http/errorHandler.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/FileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useClassinExam.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableSelect.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useAttainment.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/LmsEditor.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/files/CourseFileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/files/FileTable.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/files/FileFooter.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/courseFile/useCourseFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/stores/useCourseFileStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useSaveAsRepo.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewInfo.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewBtn.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseViewContainer.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewInfo.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewBtn.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseSetting.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/settings/Info.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/AuthManage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/repoOrder/PurchaseRepoDetail.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/useAuthCourse.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/ClientExam.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/stores/useUserStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/stores/useWorkSpaceSlideStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/stores/useUserStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/store/useClientStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/stores/useLmsStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useHistoryView.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/layout.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useRepoForks.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseApplyLms.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/stores/useCourseStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/FileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useClassinExam.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/FileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useClassinExam.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/http/errorHandler.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/guard/courseGuard.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/FileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useClassinExam.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/http/errorHandler.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/search/SearchResultItem.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/useColumns.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/Header.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/DefaultHeader.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/layout/default/defaultHeader/UserNotify.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/views/settings/SpaceSetting.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/contribute/ContributeDetail.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/extra.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/LmsEditor.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/lmsEdit/AttachmentList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/ResourceListMore.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/files/useFileOperate.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseFiles.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/LmsEditor.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/lmsEdit/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/answerCardUploadFile/UploadFileButtonList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/activityEdit/useUploadFileEdit.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/LmsEditor.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/lmsEdit/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/ResourceList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/LmsEditor.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/lmsEdit/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/activityEdit/uploadFile.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/LmsEditor.tsx --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsDomRef.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/files/CourseFileList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/components/files/CreateFileInCourse.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/files/useCreateFileInCourse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/views/HistoryVisions.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseContent.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseBaseInfo.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseCollaborator.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/detail/CourseContributer.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/CourseSetup.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/components/AgreementJump.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/CourseSetup.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/components/bg-image/SetImage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/components/bg-image/LocalUpload.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/CourseSetup.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/components/bg-image/SetImage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/components/bg-image/OfficialGallery.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/FullscreenPreview/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/FullscreenPreview/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/BlockPreview/AudioBlock.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewInfo.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewBtn.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/baseInfo/useCourseViewBtn.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseView.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewInfo.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/baseInfo/CourseViewBtn.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/baseInfo/useCourseViewBtn.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCurriculum.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/Lms.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/activityType/ActivityReadStatus.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/activityType/Record.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/widget/ActivityFile.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/BlockPreview/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/Lms.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/activityType/ActivityReadStatus.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/activityType/Record.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/Lms/widget/ActivityFile.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/BlockPreview/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/BlockPreview/ImgBlock.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/detail/CourseTop.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/CourseSetting.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/ExploreDetail.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/CommunityDynamic.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/components/community/AuthorAndCourse.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/CommunityDynamic.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/components/CommunityList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/ClientApply.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/views/Manage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/ButtonList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/courseModal/OrgIndex.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/views/Manage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/ButtonList.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/courseModal/OrgIndex.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/courseModal/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/CourseManage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/AuthManage.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/repoOrder/PurchaseRepoDetail.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/authCourse/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/repoOrder/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/repoOrder/OrderDetail.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/repoOrder/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/views/ApplyOrganization.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/ApplyOrgForm.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/views/ApplyOrganization.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/ApplyOrgSettledForm.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/views/User.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/components/UserInforTab.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/components/UserSearch.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/views/settings/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/application/useScreenWitch.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/views/settings/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/routes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/ClientExam.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/Brand.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/BrandMobile.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/BrandVipModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/Brand.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/BrandMobile.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/router/index.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/views/Brand.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/client.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/usePreferedTag.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/user/application/useUserHook.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/application/useGlobalSearch.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/home/application/useGlobalSearch.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/settings/ChangeCourseVisible.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCardEdit.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/detail/courseTop.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/settings/ChangeCourseVisible.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCardEdit.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/AddMemberModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/BatchAddMemberModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/InviteLinkModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/settings/OrgAuth.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/settings/OrgBase.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/statistics/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/statistics/PieChartPanel.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/statistics/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/team/OrgTeam.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/stores/useOrgStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCard.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/CourseCardEdit.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseTemplate.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableSelect.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/files/useFileSearch.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useTableSelect.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useFIleState.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/xid.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/xid.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/xid.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/stores/useFileDropDownStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useFileListFormModal.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useAttainment.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsFormData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useHomeworkAnswer.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useAttachmentList.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/file.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/PreviewFile.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/List.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/InviteLinkModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/members/OperateMemberModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/settings/OrgAuth.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/settings/BindClassinInstitution.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/common/utils/constants/componentList.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/components/settings/OrgAuth.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/org/application/org.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/contentDiffTypes.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useAttainmentDiff.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useDetailComoare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/compareManager/useCompareManager.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/extra.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/extra.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/contion.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useAttainmentDiff.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useAttainmentDiff.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useDetailComoare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useScoreDiff.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/extra.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/contion.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/application/useCourseCompare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useHeadDiff.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useDefaultUnit.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/usePreviewPosition.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useContentDiffData.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/extra.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/contion.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useCollapse.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useAttainmentDiff.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/useDetailComoare.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/compareManager/useCompareManager.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts",
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/utils/extra.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/contentDiff/utils.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/compareManager/useCompareManager.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/examDiff/useExamDiffData.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsDataSearch.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsDataSearch.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/stores/useStudentViewStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/useLmsDataSearch.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/courseFile/useCourseFile.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/courseFile/useCourseFile.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/stores/useCourseFileStore.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/src/lms/application/courseFile/useCourseFile.ts",
          ],
          "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/index.vue" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/index.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/detail/CourseTop.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/components/courseTemplate/CourseTemplateRenameModal.vue --> /Users/lezhao/EEO/file-reference-analysis/examples/src/course/views/detail/index.vue",
          ],
        },
        "unusedFiles": [
          "/Users/lezhao/EEO/file-reference-analysis/src/analyze.ts",
          "/Users/lezhao/EEO/file-reference-analysis/src/cli.ts",
          "/Users/lezhao/EEO/file-reference-analysis/src/config.ts",
          "/Users/lezhao/EEO/file-reference-analysis/src/index.ts",
          "/Users/lezhao/EEO/file-reference-analysis/src/regex.ts",
          "/Users/lezhao/EEO/file-reference-analysis/src/type.ts",
          "/Users/lezhao/EEO/file-reference-analysis/src/utils.ts",
        ],
      }
    `)
  })

  it('test circular', async () => {
    expect(await analyze(['./examples/fixtures/index.ts'], {
      alias: {
        '@': './examples/fixtures'
      },
      supSuffix: ['.ts']
    })).toMatchInlineSnapshot(`
      {
        "circularDepMap": Map {
          "/Users/lezhao/EEO/file-reference-analysis/examples/fixtures/a.ts" => [
            "/Users/lezhao/EEO/file-reference-analysis/examples/fixtures/a.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/fixtures/b.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/fixtures/c.ts --> /Users/lezhao/EEO/file-reference-analysis/examples/fixtures/a.ts",
          ],
        },
        "unusedFiles": [],
      }
    `)
  })
})

describe('define config', () => {
  it('test define config', async () => {
    const config = defineConfig({
      entry: './src/main.ts',
      exclude: ['**/services/**/*'],
      supSuffix: ['.ts', '.tsx'],
      alias: {
        '@': './src'
      }
    })
    expect(config).toMatchInlineSnapshot(`
      {
        "alias": {
          "@": "./src",
        },
        "entry": "./src/main.ts",
        "exclude": [
          "**/services/**/*",
        ],
        "supSuffix": [
          ".ts",
          ".tsx",
        ],
      }
    `)
  }
  )
})